services:
  api:
    build: .
    container_name: star-wars-api
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev 

  redis:
    image: 'redis:7.0-alpine'
    container_name: star-wars-redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
